- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-litmus-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-octavia-tripleo-standalone:
            voting: false

- nodeset:
    name: puppet-octavia-tripleo-single-node-centos-8-stream-nested-virt
    nodes:
      - name: primary
        label: nested-virt-centos-8-stream
    groups:
      - name: switch
        nodes:
          - primary
      - name: peers
        nodes: []

# redefine tripleo-ci-centos-8-scenario010-standalone with tripleo-puppet-ci
# job as its base.
- job:
    name: puppet-octavia-tripleo-standalone
    parent: tripleo-puppet-ci-centos-8-standalone
    nodeset: puppet-octavia-tripleo-single-node-centos-8-stream-nested-virt
    description: |
      TripleO standalone Job running Octavia specific Tempest tests.
    vars:
      build_container_images: true
      tags:
        - build
        - standalone
        - octavia
        - nested-virt
      featureset: '062'
      standalone_ceph: true
      featureset_override:
        run_tempest: false
        tempest_test_whitelist:
          - 'octavia_tempest_plugin.tests.scenario.v2.test_healthmonitor'
          - 'octavia_tempest_plugin.tests.scenario.v2.test_listener'
          - 'octavia_tempest_plugin.tests.scenario.v2.test_member'
          - 'octavia_tempest_plugin.tests.scenario.v2.test_load_balancer'
        use_os_tempest: true
        validate_services: false
        standalone_environment_files:
          - 'environments/low-memory-usage.yaml'
          - 'ci/environments/scenario010-standalone.yaml'
          - 'ci/environments/octavia-kvm.yaml'
